# This is a basic workflow to help you get started with Actions

name: CI & CD

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request closed events but only for the "main" branch
  pull_request:
    branches: [ "main" ]
    types: ["closed"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      REACT_APP_API_URL: ''

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Intsall node v16
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          
      # Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./invitation-frontend
        run: npm install
        
      # # Build frontend
      # - name: Build frontend
      #   working-directory: ./invitation-frontend
      #   run: npm run build

      # Build frontend without eslint
      - name: Build frontend without eslint
        working-directory: ./invitation-frontend
        run: npm run build-without-eslint

      # Install backend dependencies
      - name: Install backend dependencies
        working-directory: ./invitation-backend
        run: npm install
        
      # Build backend
      - name: Build backend
        working-directory: ./invitation-backend
        run: npm run build
        
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: invitation-artifacts
          path: |
            ./
            !./invitation-frontend/node_modules/*
            !./invitation-backend/node_modules/*
  
  # This workflow called "release"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Release workflow only runs after build workflow success.
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v3
      
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: invitation-artifacts

      - name: ssh deploy
      # You may pin to the exact commit or the version.
      # uses: easingthemes/ssh-deploy@c711f2c3391cac2876bf4c833590077f02e4bcb8
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          # Private Key
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          # Remote host
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          # Remote user
          REMOTE_USER: ${{ secrets.SSH_USER }}
          # Target directory
          TARGET: ${{ secrets.TARGET_PATH }}
          # Source
          SOURCE: /
          # Excludes
          EXCLUDE: "/node_modules/"
          
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts
        
      - name: Preparing the backend.
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.SSH_HOST }}
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          command: |
            cd ./mobile-invitation/invitation-backend
            npm install --production
